spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  profiles:
    include: oauth, mysql

app:
  auth:
    token-secret: 926D96C90030DD58429D2751AC1BDBBC
    token-expiration-msec: 864000000
  oauth2:
    authorized-redirect-uris: http://localhost:8080/oauth2/redirect